tunnel: monitoring-tunnel
credentials-file: /home/awash/.cloudflared/<your-tunnel-UUID>.json

ingress:
  - hostname: grafana.awashmasketech.co.uk
    service: http://localhost:********
  - hostname: prom.awashmasket****ech.co.uk*****
    service: http://localhost:********
  - service: http_status:404  # catch-all
