services:
  web:
    ports:
      - "127.0.0.1:8081:80"   # different port from production
    environment:
      - VIRTUAL_HOST=staging.awashmasketech.co.uk
      - LETSENCRYPT_HOST=staging.awashmasketech.co.uk   # future if adding certs
